blog/urls.py
from django.urls import path

from blog.views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
)
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogListView.as_view(), name="blog_list"),
    path("<slug:slug>/", BlogDetailView.as_view(), name="blog_detail"),
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("update/<slug:slug>/", BlogUpdateView.as_view(), name="blog_update"),
    path("delete/<slug:slug>/", BlogDeleteView.as_view(), name="blog_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("sending_emails.urls", namespace="sending_emails")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sending_emails/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from sending_emails.views import ClientsListView, ClientsDetailView, ClientCreateView, ClientUpdateView, \
    ClientDeleteView, MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView, \
    MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView, HomeView, LogListView

app_name = "sending_emails"

urlpatterns = [
    path("", HomeView.as_view(), name="home_page"),
    path("clients/", ClientsListView.as_view(), name="clients_list"),
    path("client/<int:pk>/", ClientsDetailView.as_view(), name="client"),
    path("create/", ClientCreateView.as_view(), name="client_create"),
    path("update/<int:pk>/", ClientUpdateView.as_view(), name="client_update"),
    path("delete/<int:pk>/", ClientDeleteView.as_view(), name="client_delete"),

    path("messages/", MessageListView.as_view(), name="messages_list"),
    path("message/<int:pk>/", cache_page(60)(MessageDetailView.as_view()), name="message"),
    path("message/create/", MessageCreateView.as_view(), name="message_create"),
    path("message/update/<int:pk>/", MessageUpdateView.as_view(), name="message_update"),
    path("message/delete/<int:pk>/", MessageDeleteView.as_view(), name="message_delete"),

    path("mailings/", MailingListView.as_view(), name="mailings_list"),
    path("mailing/<int:pk>/", MailingDetailView.as_view(), name="mailing"),
    path("mailing/create/", MailingCreateView.as_view(), name="mailing_create"),
    path("mailing/update/<int:pk>/", MailingUpdateView.as_view(), name="mailing_update"),
    path("mailing/delete/<int:pk>/", MailingDeleteView.as_view(), name="mailing_delete"),

    path("log/", LogListView.as_view(), name="log_list"),
]

sending_emails/models.py
from django.utils import timezone
from django.db import models

from users.models import User


class Clients(models.Model):
    email = models.EmailField(unique=True, verbose_name='Почта')
    fio = models.CharField(max_length=50, verbose_name='ФИО')
    comment = models.TextField(blank=True, verbose_name='Коммент')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Владелец', null=True, blank=True)

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    def __str__(self):
        return f'{self.fio}: {self.email} - {self.comment}'


class Message(models.Model):
    subject_message = models.CharField(max_length=80, verbose_name='Тема письма')
    message = models.TextField(verbose_name='Текст письма')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Владелец', null=True, blank=True)

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
        permissions = [
            ('view_mailing', 'Может просматривать любые рассылки.')]

    def __str__(self):
        return f'{self.subject_message} - {self.message}'


class Mailing(models.Model):
    period_variants = (
        ('per_day', 'раз в день'),
        ('per_week', 'раз в неделю'),
        ('per_month', 'раз в месяц')
    )

    status_variants = (
        ('created', 'создана'),
        ('executing', 'запущена'),
        ('finished', 'закончена успешно'),
    )

    start_time = models.DateTimeField(default=timezone.now, verbose_name='Начало рассылки', help_text="Формат DD.MM.YYYY HH:MM:SS",)
    end_time = models.DateTimeField(null=True, blank=True, verbose_name='Конец рассылки', help_text="Формат DD.MM.YYYY HH:MM:SS",)
    next_time_mailing = models.DateTimeField(null=True, blank=True, verbose_name='Следующее время рассылки', help_text="Формат DD.MM.YYYY HH:MM:SS",)
    frequency = models.CharField(max_length=50, choices=period_variants, default='per_day',
                                 verbose_name='периодичность')
    mailing_status = models.CharField(max_length=80, choices=status_variants, default='created',
                                      verbose_name='статус рассылки')
    clients = models.ManyToManyField(Clients, related_name='mailing', verbose_name='Клиенты для рассылки')
    message = models.ForeignKey(Message, verbose_name='Cообщение', on_delete=models.CASCADE, blank=True, null=True)

    owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Владелец', null=True, blank=True)
    is_active = models.BooleanField(default=True, verbose_name='Рассылка разрешена')

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [
            ('deactivate_mailing', 'Can deactivate mailing'),
        ]

    def __str__(self):
        return f'{self.start_time} - {self.end_time} - {self.frequency} - {self.mailing_status}'


class MailingAttempt(models.Model):
    status_variants = (
        ('successfully', 'успешно'),
        ('not_successful', 'не успешно'),
    )

    last_attempt = models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')
    status = models.CharField(choices=status_variants, default=None, verbose_name='статус попытки')
    mail_response = models.CharField(max_length=100, verbose_name='ответ почтового сервера', blank=True, null=True)
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name="Рассылка")

    class Meta:
        verbose_name = 'Попытка рассылки'
        verbose_name_plural = 'Попытки рассылок'
        permissions = [
            ('change_is_active', 'Может отключать рассылки.'), ]

    def __str__(self):
        return f'{self.last_attempt} - {self.status} - {self.mail_response}'

sending_emails/forms.py
from django import forms
from .models import Clients, Mailing, Message, MailingAttempt
from django.forms import BooleanField


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs["class"] = "form-check-input"
            else:
                fild.widget.attrs["class"] = "form-control"


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Clients
        exclude = ('owner',)


class MailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        exclude = ('owner', 'is_active', 'next_time_mailing',)

    def __init__(self, *args, **kwargs):
        """Выводим только созданные пользователем клиентов и сообщения"""
        self.request = kwargs.pop("request")
        user = self.request.user
        super().__init__(*args, **kwargs)
        self.fields["clients"].queryset = Clients.objects.filter(owner=user)
        self.fields["message"].queryset = Message.objects.filter(owner=user)


class AdminMailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        exclude = ('owner', 'is_active', 'next_time_mailing',)


class ManagerMailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ('is_active',)


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        exclude = ('owner',)


class AttemptForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingAttempt
        fields = ('status', 'mail_response',)

sending_emails/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView, TemplateView,
)
import random
from django.forms import inlineformset_factory
from blog.models import Blog
from sending_emails.forms import ClientForm, MessageForm, MailingForm, ManagerMailingForm, AttemptForm, AdminMailingForm
from sending_emails.models import Clients, Message, Mailing, MailingAttempt


class ClientsListView(LoginRequiredMixin, ListView):
    """
    Контроллер отвечающий за отображение списка клиентов
    """
    model = Clients

    def get_queryset(self, queryset=None):
        queryset = super().get_queryset()
        user = self.request.user
        if not user.is_superuser:
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class ClientsDetailView(LoginRequiredMixin, DetailView):
    """
    Контроллер отвечающий за отображение клиента
    """
    model = Clients

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            return self.object
        raise PermissionDenied


class ClientCreateView(LoginRequiredMixin, CreateView):
    """
    Контроллер отвечающий за создание клиента
    """
    model = Clients
    form_class = ClientForm
    success_url = reverse_lazy('sending_emails:clients_list')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контроллер отвечающий за редактирование клиента
    """
    model = Clients
    form_class = ClientForm

    def get_success_url(self):
        return reverse('sending_emails:client', args=[self.kwargs.get('pk')])

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    """
    Контроллер отвечающий за удаление клиента
    """
    model = Clients
    success_url = reverse_lazy('sending_emails:clients_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


# ---------------------------------------------------------------------------------------------

class MessageListView(LoginRequiredMixin, ListView):
    """
    Контроллер отвечающий за отображение списка сообщений
    """
    model = Message

    def get_queryset(self, queryset=None):
        queryset = super().get_queryset()
        user = self.request.user
        if not user.is_superuser:
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class MessageDetailView(LoginRequiredMixin, DetailView):
    """
    Контроллер отвечающий за отображение сообщения
    """
    model = Message

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class MessageCreateView(LoginRequiredMixin, CreateView):
    """
    Контроллер отвечающий за создание сообщения
    """
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('sending_emails:messages_list')

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контроллер отвечающий за редактирование сообщение
    """
    model = Message
    form_class = MessageForm

    def get_success_url(self):
        return reverse('sending_emails:message', args=[self.kwargs.get('pk')])

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    """
    Контроллер отвечающий за удаление сообщения
    """
    model = Message
    success_url = reverse_lazy('sending_emails:messages_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


# ----------------------------------------------------------------------------------------------


class MailingListView(LoginRequiredMixin, ListView):
    """
    Контроллер отвечающий за отображение списка рассылок
    """
    model = Mailing

    def get_queryset(self, queryset=None):
        queryset = super().get_queryset()
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='manager'):
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class MailingDetailView(LoginRequiredMixin, DetailView):
    """
    Контроллер отвечающий за отображение рассылки
    """
    model = Mailing

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        VersionFormset = inlineformset_factory(
            Mailing,
            MailingAttempt,
            AttemptForm,
            extra=0,
            can_delete=False,
        )
        context_data["formset"] = VersionFormset(instance=self.object)
        return context_data


    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='manager') and user != self.object.owner:
            raise PermissionDenied
        else:
            return self.object


class MailingCreateView(LoginRequiredMixin, CreateView):
    """
    Контроллер отвечающий за создание рассылки
    """
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('sending_emails:mailings_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.owner = user
        mailing.save()
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контроллер отвечающий за редактирование рассылки
    """
    model = Mailing
    form_class = MailingForm

    def get_form_kwargs(self):
        user = self.request.user
        if user == self.object.owner:
            kwargs = super().get_form_kwargs()
            kwargs.update({'request': self.request})
            return kwargs
        else:
            kwargs = super().get_form_kwargs()
            return kwargs

    def get_success_url(self):
        return reverse('sending_emails:mailing', args=[self.kwargs.get('pk')])

    def get_form_class(self):
        """
        Функция, определяющая поля для редактирования в зависимости от прав пользователя
        """
        user = self.request.user
        if user == self.object.owner:
            return MailingForm
        elif user.is_superuser:
            return AdminMailingForm
        elif user.has_perm('sending_emails.deactivate_mailing'):
            return ManagerMailingForm
        else:
            raise PermissionDenied


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    """
    Контроллер отвечающий за удаление расылки
    """
    model = Mailing
    success_url = reverse_lazy('sending_emails:mailings_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class HomeView(TemplateView):
    """
    Контроллер главной страницы сайта
    """
    template_name = 'sending_emails/index.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        mailings = Mailing.objects.all()
        clients = Clients.objects.all()
        blog_list = list(Blog.objects.all())
        random.shuffle(blog_list)
        context_data['all_mailings'] = mailings.count()
        context_data['active_mailings'] = mailings.filter(mailing_status='executing').count()
        context_data['active_clients'] = clients.values('email').distinct().count()

        context_data['blog_list'] = blog_list[:3]
        return context_data


class LogListView(LoginRequiredMixin, ListView):
    """
    Контроллер отвечающий за отображение списка попыток рассылок
    """
    model = MailingAttempt

sending_emails/templates/sending_emails/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>МАГАЗИН</title>
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>

{% include 'sending_emails/includes/include_menu.html' %}


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис рассылок писем</h1>
    <p class="lead">Сервис рассылок - это отличный вариант привлечь новых клиентов</p>
</div>

<div class="container">

    {% block content %}
    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-3 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
            <div class="col-3 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-3 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-3 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href=#>Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static '/js/popper.min.js' %}"></script>
<script src="{% static '/js/bootstrap.min.js' %}"></script>
</body>
</html>

sending_emails/templates/sending_emails/clients_confirm_delete.html
{% extends 'sending_emails/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col">
    </div>
    <div class="col-5">
      <form method="post">
          {% csrf_token %}
          <p>Хотите удалить {{ object.fio }}?</p>
          <button class="btn btn-primary" role="button">Подтвердить</button>
          <a href="{% url 'sending_emails:clients_list' %}" class="btn btn-primary" role="button">Отменить</a>
      </form>
    </div>
    <div class="col">
    </div>
  </div>
{% endblock %}

sending_emails/templates/sending_emails/clients_detail.html
{% extends 'sending_emails/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col">
    </div>
    <div class="col-5">
      <h3 class="card-text">{{ object.fio }}</h3>
      <p class="card-text">{{ object.email }}</p>
      <p class="card-text">{{ object.comment }}</p>
    </div>
    <div class="col">
    </div>
  </div>
{% endblock %}

sending_emails/templates/sending_emails/clients_form.html
{% extends 'sending_emails/base.html' %}
{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Клиент</h4>
                    </div>
                        <div class="card_body">
                              {% csrf_token %}
                              {{ form.as_p }}
                              <button class="btn btn-primary" role="button">
                                  {% if object %}
                                    Сохранить
                                  {% else %}
                                    Создать нового клиента
                                  {% endif %}
                              </button>
                        </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock%}

sending_emails/templates/sending_emails/clients_list.html
{% extends 'sending_emails/base.html' %}
{% load my_tags %}

{% block content %}
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <h3 class="card-text">{{ object.fio }}</h3>
              <p class="card-text">{{ object.comment|slice:100 }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a class="btn btn-primary" href="{% url 'sending_emails:client' object.pk %}" role="button">Просмотр</a>
                  <p>|</p>
                  <a class="btn btn-primary" href="{% url 'sending_emails:client_update' object.pk %}" role="button">Изменить</a>
                  <p>|</p>
                  <a class="btn btn-primary" href="{% url 'sending_emails:client_delete' object.pk %}" role="button">Удалить</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      </div>
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
          {% if user.is_authenticated %}
          <a class="btn btn-primary" href="{% url 'sending_emails:client_create' %}" role="button">Создать нового клиента</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

sending_emails/templates/sending_emails/index.html
{% extends 'sending_emails/base.html' %}
{% load my_tags %}

{% block content %}
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in blog_list %}
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ object.preview | media_filter }}">
            <div class="card-body">
              <h3 class="card-text">{{ object.heading_blog }}</h3>
              <p class="card-text">{{ object.content_blog|slice:100 }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a class="btn btn-primary" href="{% url 'blog:blog_detail' object.slug %}" role="button">Посмотреть</a>
                  <p>|</p>
                  {% if user.is_superuser %}
                  <a class="btn btn-primary" href="{% url 'blog:blog_update' object.slug %}" role="button">Изменить</a>
                  <p>|</p>
                  <a class="btn btn-primary" href="{% url 'blog:blog_delete' object.slug %}" role="button">Удалить</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
          <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Просмотреть весь наш блог</a>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row align-items-start">
        <div class="col">
          <div class="card">
              <div class="card-body">
                <h4 class="card-title">Количество рассылок на сайте</h4>
                <h6 class="card-subtitle mb-2 text-muted"></h6>
                <p class="card-text">
                  {{all_mailings}}
                </p>
                <a href="/mailings/" class="card-link">Перейти в рассылки</a>
              </div>
          </div>
        </div>
        <div class="col">
          <div class="card">
              <div class="card-body">
                <h4 class="card-title">Количество активных рассылок</h4>
                <h6 class="card-subtitle mb-2 text-muted"></h6>
                <p class="card-text">
                  {{active_mailings}}
                </p>
                <a href="/mailings/" class="card-link">Перейти в рассылки</a>
              </div>
          </div>
        </div>
        <div class="col">
          <div class="card">
              <div class="card-body">
                <h4 class="card-title">Количество уникальных клиентов</h4>
                <h6 class="card-subtitle mb-2 text-muted"></h6>
                <p class="card-text">
                  {{active_clients}}
                </p>
                <a href="/clients/" class="card-link">Перейти к клиентам</a>
              </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

sending_emails/templates/sending_emails/mailing_list.html
{% extends 'sending_emails/base.html' %}
{% load my_tags %}

{% block content %}
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <h4 class="card-text">С {{ object.start_time }}</h4>
              <h4 class="card-text">ПО {{ object.end_time }}</h4>
              <p class="card-text">{{ object.mailing_status }}</p>
              <p class="card-text">-------------------------</p>
              <p class="card-text">Тема письма: {{ object.message.subject_message }}</p>
              <p class="card-text">-------------------------</p>
              {% for version in object.clients.all %}
              <p>Клиент для рассылки: {{version.fio}} </p>
              {% endfor %}

              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a class="btn btn-primary" href="{% url 'sending_emails:mailing' object.pk %}" role="button">Просмотр</a>
                  <p>|</p>
                  <a class="btn btn-primary" href="{% url 'sending_emails:mailing_update' object.pk %}" role="button">Изменить</a>
                  <p>|</p>
                  <a class="btn btn-primary" href="{% url 'sending_emails:mailing_delete' object.pk %}" role="button">Удалить</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      </div>
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
          {% if user.is_authenticated %}
          <a class="btn btn-primary" href="{% url 'sending_emails:mailing_create' %}" role="button">Создать новую рассылку</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

sending_emails/templates/sending_emails/message_detail.html
{% extends 'sending_emails/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col">
    </div>
    <div class="col-5">
      <h3 class="card-text">{{ object.subject_message }}</h3>
      <p class="card-text">{{ object.message }}</p>
    </div>
    <div class="col">
    </div>
  </div>
{% endblock %}

sending_emails/templates/sending_emails/message_list.html
{% extends 'sending_emails/base.html' %}
{% load my_tags %}

{% block content %}
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <h3 class="card-text">{{ object.subject_message }}</h3>
              <p class="card-text">{{ object.message|slice:100 }}</p>

              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a class="btn btn-primary" href="{% url 'sending_emails:message' object.pk %}" role="button">Просмотр</a>
                  <p>|</p>
                  <a class="btn btn-primary" href="{% url 'sending_emails:message_update' object.pk %}" role="button">Изменить</a>
                  <p>|</p>
                  <a class="btn btn-primary" href="{% url 'sending_emails:message_delete' object.pk %}" role="button">Удалить</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      </div>
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
          {% if user.is_authenticated %}
          <a class="btn btn-primary" href="{% url 'sending_emails:message_create' %}" role="button">Создать новое сообщение</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}