blog/urls.py
from django.urls import path

from blog.views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
)
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogListView.as_view(), name="blog_list"),
    path("<slug:slug>/", BlogDetailView.as_view(), name="blog_detail"),
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("update/<slug:slug>/", BlogUpdateView.as_view(), name="blog_update"),
    path("delete/<slug:slug>/", BlogDeleteView.as_view(), name="blog_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("sending_emails.urls", namespace="sending_emails")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    heading_blog = models.CharField(
        max_length=150, verbose_name="Заголовок", help_text="Введите заголовок"
    )
    slug = models.CharField(
        max_length=150,
        null=True,
        blank=True,
        verbose_name="Человекопонятный URL",
        help_text="Человекопонятный URL",
    )
    content_blog = models.TextField(
        verbose_name="Содержимое", help_text="Введите содержимое"
    )
    preview = models.ImageField(
        upload_to="media/blog/",
        null=True,
        blank=True,
        verbose_name="Изображение",
        help_text="Укажите изображение",
    )
    created_at = models.DateField(
        auto_now_add=True,
        null=True,
        blank=True,
        verbose_name="Дата публикации",
        help_text="Введите дату публикации",
    )
    count_views = models.PositiveIntegerField(
        default=0,
        verbose_name="Количество просмотров",
    )

    def __str__(self):
        return self.heading_blog

    class Meta:
        verbose_name = "Блоговая запись"
        verbose_name_plural = "Блоговые записи"

blog/forms.py
from blog.models import Blog
from sending_emails.forms import StyleFormMixin
from django import forms


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        exclude = ('count_views', 'slug',)

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from pytils.translit import slugify

from blog.forms import BlogForm
from blog.models import Blog


class BlogListView(ListView):
    model = Blog


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_views += 1
        self.object.save()
        return self.object


class BlogCreateView(CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy("blog:blog_list")

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.heading_blog)
            new_blog.save()
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = (
        "heading_blog",
        "content_blog",
        "preview",
    )

    def get_success_url(self):
        return reverse("blog:blog_detail", args=[self.kwargs.get("pk")])


class BlogDeleteView(DeleteView):
    model = Blog
    fields = (
        "heading_blog",
        "content_blog",
    )
    success_url = reverse_lazy("blog:blog_list")

blog/templates/blog/blog_confirm_delete.html
{% extends 'sending_emails/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col">
    </div>
    <div class="col-5">
      <form method="post">
          {% csrf_token %}
          <p>Хотите удалить {{ object.heading_blog }}?</p>
          <button class="btn btn-primary" role="button">Подтвердить</button>
          <a href="{% url 'blog:blog_list' %}" class="btn btn-primary" role="button">Отменить</a>
      </form>
    </div>
    <div class="col">
    </div>
  </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'sending_emails/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col">
    </div>
    <div class="col-5">
      <img src="{{ object.preview | media_filter }}">
      <h3 class="card-text">Заголовок - {{ object.heading_blog }}</h3>
      <p class="card-text">Данные - {{ object.content_blog }}</p>
      <p class="card-text">Просмотры - {{ object.count_views }}</p>
    </div>
    <div class="col">
    </div>
  </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'sending_emails/base.html' %}
{% block content %}
<div class="row">
    <div class="col">
    </div>
    <div class="col-5">
      <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="btn btn-primary" role="button">
              {% if object %}
                Сохранить
              {% else %}
                Создать новую запись
              {% endif %}
          </button>
      </form>
    </div>
    <div class="col">
    </div>
  </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'sending_emails/base.html' %}
{% load my_tags %}

{% block content %}
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ object.preview | media_filter }}">
            <div class="card-body">
              <h3 class="card-text">{{ object.heading_blog }}</h3>
              <p class="card-text">{{ object.content_blog|slice:100 }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a class="btn btn-primary" href="{% url 'blog:blog_detail' object.slug %}" role="button">Посмотреть</a>
                  <p>|</p>
                  {% if user.is_superuser %}
                  <a class="btn btn-primary" href="{% url 'blog:blog_update' object.slug %}" role="button">Изменить</a>
                  <p>|</p>
                  <a class="btn btn-primary" href="{% url 'blog:blog_delete' object.slug %}" role="button">Удалить</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
          {% if user.is_superuser %}
          <a class="btn btn-primary" href="{% url 'blog:blog_create' %}" role="button">Создать новую запись</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}