blog/urls.py
from django.urls import path

from blog.views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
)
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogListView.as_view(), name="blog_list"),
    path("<slug:slug>/", BlogDetailView.as_view(), name="blog_detail"),
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("update/<slug:slug>/", BlogUpdateView.as_view(), name="blog_update"),
    path("delete/<slug:slug>/", BlogDeleteView.as_view(), name="blog_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("sending_emails.urls", namespace="sending_emails")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from django.contrib.auth.views import LogoutView

from users.views import RegisterView, email_verification, LoginView, PasswordReset, UserListView, blocking_user

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name='users/login.html'), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),
    path("register/", RegisterView.as_view(), name='register'),
    path("email-confirm/<str:token>/", email_verification, name='email-confirm'),
    path("reset_password/", PasswordReset.as_view(), name='reset_password'),
    path('users_list/', UserListView.as_view(), name='users_list'),
    path('blocking_user/<int:pk>/', blocking_user, name='blocking_user'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    username = None
    email = models.EmailField(verbose_name="email", unique=True)
    avatar = models.ImageField(
        upload_to="media/users/",
        null=True,
        blank=True,
        verbose_name="Аватар",
        help_text="Укажите аватар",
    )
    telephone = models.CharField(
        max_length=35,
        verbose_name="телефон",
        help_text="Введите телефон",
        null=True,
        blank=True,
    )
    country = models.CharField(
        max_length=35,
        verbose_name="страна",
        help_text="Введите страну",
        null=True,
        blank=True,
    )
    token = models.CharField(
        max_length=50,
        verbose_name="токен",
        null=True,
        blank=True,
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f"{self.email}"

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        permissions = [
            ('deactivate_user', 'Can deactivate user'),
            ('view_all_users', 'Can view all users'),
        ]

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from sending_emails.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

users/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import CreateView
from users.forms import UserRegisterForm
from users.models import User
from django.urls import reverse_lazy, reverse
from django.core.mail import send_mail
import secrets
from config.settings import EMAIL_HOST_USER
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.forms import PasswordResetForm
from django.views.generic import ListView


class LoginView(BaseLoginView):
    template_name = 'users/login.html'


class PasswordReset(PasswordResetView):
    model = User
    form_class = PasswordResetForm
    template_name = 'users/reset_password.html'

    def form_valid(self, form):
        if form.is_valid():
            email = form.cleaned_data['email']
            user = User.objects.get(email=email)
            if user:
                password = User.objects.make_random_password(12)
                user.set_password(password)
                user.save()
                send_mail(
                    subject="Восстановление пароля",
                    message=f"Ваш новый пароль: {password}",
                    from_email=EMAIL_HOST_USER,
                    recipient_list=[user.email],
                )
            return redirect(reverse("users:login"))


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/email-confirm/{token}/"
        send_mail(
            subject='Подтверждение почты',
            message=f"Перейди по ссылке для подтверждения почты {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))


class UserListView(PermissionRequiredMixin, ListView):
    model = User
    permission_required = 'users.view_all_users'


@permission_required('users.deactivate_user')
def blocking_user(request, pk):
    user = User.objects.get(pk=pk)
    if user.is_active:
        user.is_active = False
    else:
        user.is_active = True
    user.save()
    return redirect(reverse('users:users_list'))

users/templates/users/login.html
{% extends 'sending_emails/base.html' %}
{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Авторизация</h4>
                    </div>
                        <div class="card_body">
                              {% csrf_token %}
                              {{ form.as_p }}
                              <button class="btn btn-primary" role="button">
                                    Вход
                              </button>
                              <a class="btn btn-dark" href="{% url 'users:reset_password' %}">Забыл пароль</a>

                        </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock%}

users/templates/users/register.html
{% extends 'sending_emails/base.html' %}
{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Регистрация</h4>
                    </div>
                        <div class="card_body">
                              {% csrf_token %}
                              {{ form.as_p }}
                              <button class="btn btn-primary" role="button">
                                    Регистрация
                              </button>
                        </div>
                </div>
            </div>

        </div>
    </form>
</div>
{% endblock%}

users/templates/users/reset_password.html
{% extends 'sending_emails/base.html' %}
{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Восстановление пароля</h4>
                    </div>
                        <div class="card_body">
                              {% csrf_token %}
                              {{ form.as_p }}
                              <button class="btn btn-primary" role="button">
                                    Будет отправлен новый пароль на почту
                              </button>
                        </div>
                </div>
            </div>

        </div>
    </form>
</div>
{% endblock%}

users/templates/users/user_list.html
{% extends 'sending_emails/base.html'%}
{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Список пользователей</h1>
    </div>
</section>
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">Email</th>
        <th scope="col">Статус</th>
        <th scope="col">Изменение сатуса</th>
    </tr>
    </thead>
    <tbody>
    {% for user in object_list %}
    <tr>
        <td>{{ user.email }}</td>
        <td>{{ user.is_active }}</td>
        <td>{% if perms.users.deactivate_user %}
            {% if user.is_active %}
            <a href="{% url 'users:blocking_user' user.pk %}"
               class="btn btn-sm btn-outline-danger">Заблокировать пользователя</a>
            {% else %}
            <a href="{% url 'users:blocking_user' user.pk %}"
               class="btn btn-sm btn-outline-success">Разблокировать пользователя</a>
            {% endif %}
            {% endif %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}